### PR TITLE
Fix randomElement

### PR DESCRIPTION
**Pull request by RobLoach**

### CODE REVIEW

**Comment by thiagodemellobueno** [comment]
👍 thanks @RobLoach

**Comment by RobLoach** [comment]
@madeofpeople Will also have to make a 1.4.1 release and `npm publish`.

**Comment by thiagodemellobueno** [comment]
Already done.

**Comment by RobLoach** [comment]
:dancer: :dancer: :dancer: :dancer: :dancer: :dancer: :dancer: :dancer: :dancer: :dancer: :dancer: :dancer: :dancer:

**Pull request merged**
